### ISSUE TITLE
Latin American Death Squads trigger outside of Latin America

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-old#75] opened 2019-09-20 15:54 UTC
Those death squads have some reach. Look at the log, I got a -1 on an Iran coup. 

Is the screenshot attached? Of course it is.

![image](https://user-images.githubusercontent.com/54612963/65340792-01ea6e00-db9d-11e9-97b8-ed79fe28de6c.png)

**Comment by trevelyan** [comment] 2019-09-20 16:52
Yeah, that's the direct reading of the card, so it's how it is
implemented....

**Comment by Tuch-o** [comment] 2019-09-20 16:57
But afaik it should be Americas only

https://twilightstrategy.com/2012/11/09/latin-american-death-squads/
https://boardgamegeek.com/thread/446401/latin-american-death-squads-opponents-penalty

**Comment by trevelyan** [comment] 2019-09-20 16:58
Yeah. But we'd get complaints the other way if we changed it.

**Comment by trevelyan** [comment] 2019-09-20 16:58
And the straight reading of the card is -1 everywhere else, which sort of
makes more sense as a card tbh.

**Comment by Tuch-o** [comment] 2019-09-23 16:03
I understand, feel free to close it

**Comment by trevelyan** [comment] 2019-09-25 14:28
closing - not a bug :)

**Closed as completed by trevelyan** 2019-09-25 14:28 UTC
Labels: bug, TS
