### ISSUE TITLE
Log repeating messages

### ISSUE THREAD

**Issue by Tuch-o** [SaitoTech/saito-old#66] opened 2019-09-13 15:04 UTC
Also happens with Brezhnev.

Screenshot attached: 

![RepeatedLog](https://user-images.githubusercontent.com/54612963/64872828-dc49eb80-d615-11e9-80e6-850833aa5ba6.png)

**Comment by BearGuy** [comment] 2019-09-15 00:39
Are we able to repeatedly trigger this, or was this just a one time occurrence?

**Comment by trevelyan** [comment] 2019-09-16 14:25
it's calculating modify ops when choosing cards to show people (figuring
out if Quagmire or something else applies)

I think the easy fix is just not printing the update. It's a bit
complicated to have a further workaround, so I haven't.

Maybe we can just check the log and make sure only one of them prints ever.

>

**Comment by BearGuy** [comment] 2019-09-18 03:27
If we can't reproduce this issue, then I'm going to close it

**Comment by Tuch-o** [comment] 2019-09-25 14:37
Reopening this since I just saw it again, this time with Red Scare. I'm not sure what's triggering it, but it's definitely there. 

Look at the log in the _screenshot_ I've _attached_

![image](https://user-images.githubusercontent.com/54612963/65610737-bf9ba500-df7f-11e9-93bf-056df4481ae8.png)

**Comment by Tuch-o** [comment] 2019-09-25 17:20
Just happened again, maybe something's triggering it today. Containment this time.

Captura de pantalla adjuntada:

![image](https://user-images.githubusercontent.com/54612963/65622911-aa7d4100-df94-11e9-9f30-7cd2b173497b.png)

**Comment by trevelyan** [comment] 2019-09-26 15:39
we can easily replicate it.

i'll see if there is an easy way to fix it....

**Comment by trevelyan** [comment] 2019-09-26 15:39
the game is checking in modifyOps to see if the cards are above some OPS
level needed, probably for Quagmire or Bear Trap.

And it's printing out each time it applies the bonus.

**Comment by trevelyan** [comment] 2019-09-26 15:40
i should be able to solve it. just punted on it as low-level not too
important issue

**Comment by trevelyan** [comment] 2019-10-30 05:09
should be fixed -- added hack in updateLog() to ignore "is affected by" messages that are submitted repeatedly.

**Closed as completed by trevelyan** 2019-10-30 05:09 UTC
Labels: bug, TS
